trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'bharath1612/usc'
  tag: $(Build.BuildId)

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)

- script: |
    # Add the workspace directory to Git's safe directory list
    
    
    # Update the image tag in the deployment file
    sed -i 's|image: .*|image: bharath1612/usc:$(Build.BuildId)|' deployment.yml
    
    # Configure Git
    git config --global user.name 'bharathyadav161'
    git config --global user.email 'bharathyadav9123161@gmail.com'
    
    # Pull the latest changes
    git pull https://bharathyadav161:$(GIT_TOKEN)@github.com/bharathyadav161/usecase.git HEAD:main
    
    # Add and commit the changes
    git add deployment.yml service.yml
    git commit -m "Update image tag to $(Build.BuildId)"
    
    # Push the changes
    git push https://bharathyadav161:$(GIT_TOKEN)@github.com/bharathyadav161/usecase.git HEAD:main
  displayName: 'Update Deployment YAML with New Image Tag'
  env:
    GIT_TOKEN: $(GIT_TOKEN)