trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'bharath1612/usc'
  tag: $(Build.BuildId)

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)

- script: |
    
    
    # Update the image tag in the deployment file
    sed -i 's|image: .*|image: bharath1612/usc:$(Build.BuildId)|' deployment.yml
    
    # Configure Git
    git config --global user.name '2355333'
    git config --global user.email '2355333@cognizant.com'
    
    # Pull the latest changes
    git pull https://2355333:FgAMtmLRa4t3zbspawQX5Wq36aOgYk2M347EMSTjAHH2tsF8fiaLJQQJ99ALACAAAAA6DxLKAAASAZDOb4zy@dev.azure.com/2355333/usecase/_git/usecase HEAD:main
    
    # Add and commit the changes
    git add deployment.yml service.yml
    git commit -m "Update image tag to $(Build.BuildId)"
    
    # Push the changes
    git push https://2355333:FgAMtmLRa4t3zbspawQX5Wq36aOgYk2M347EMSTjAHH2tsF8fiaLJQQJ99ALACAAAAA6DxLKAAASAZDOb4zy@dev.azure.com/2355333/usecase/_git/usecase HEAD:main
  displayName: 'Update Deployment YAML with New Image Tag'
  env:
    AZURE_PAT: FgAMtmLRa4t3zbspawQX5Wq36aOgYk2M347EMSTjAHH2tsF8fiaLJQQJ99ALACAAAAA6DxLKAAASAZDOb4zy
