apiVersion: apps/v1
kind: Deployment
metadata:
  name: usc-deployment
  labels:
    app: usc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: usc
  template:
    metadata:
      labels:
        app: usc
    spec:
      containers:
      - name: usc-container
        image: bharath1612/usc:23
        ports:
        - containerPort: 80
